/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.thesummit.flink;

import static org.junit.Assert.*;

import org.junit.Test;

public class FlinkApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    FlinkApplication classUnderTest = new FlinkApplication();
    assertNotNull(classUnderTest);
  }
}
