/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.thesummit.flink;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;

public class FlinkApplication {

  public static void main(String[] args) throws IOException {
    HttpServer server = HttpServer.create(new InetSocketAddress(8000), 0);
    server.createContext("/main", new MyHandler());
    server.setExecutor(null);
    server.start();
    System.out.println("flink server running on port 8000");
  }
}

class MyHandler implements HttpHandler {
  public void handle(HttpExchange t) throws IOException {
    String response = "This is the response ok!";
    t.sendResponseHeaders(200, response.length());
    OutputStream os = t.getResponseBody();
    os.write(response.getBytes());
    os.close();
  }
}
