/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.thesummit.flink;

import com.sun.net.httpserver.HttpServer;
import dev.thesummit.flink.database.ConnectionPool;
import dev.thesummit.flink.database.FlinkConnectionPool;
import dev.thesummit.flink.handlers.LinkHandler;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.sql.SQLException;

public class FlinkApplication {
  // TODO: Change these to OS ENV parameters.
  static final String DB_URL = "jdbc:postgresql://localhost:5432/flink-dev";
  static final String DB_USER = "tyler";
  static final String DB_PASSWORD = "";
  private static FlinkApplication appContext = null;
  public ConnectionPool pool = null;

  public static FlinkApplication create() {

    if (FlinkApplication.appContext == null) {

      appContext = new FlinkApplication();

      try {
        appContext.pool =
            FlinkConnectionPool.create(
                FlinkApplication.DB_URL, FlinkApplication.DB_USER, FlinkApplication.DB_PASSWORD);
      } catch (SQLException e) {
        System.out.println(e);
      }
    }

    return appContext;
  }

  public static FlinkApplication getContext() {
    return appContext;
  }

  public static void main(String[] args) throws IOException {
    HttpServer server = HttpServer.create(new InetSocketAddress(8000), 0);

    FlinkApplication.create();
    // Register Route Handlers.
    server.createContext("/main", new LinkHandler());

    server.setExecutor(null);
    server.start();
    System.out.println("flink development server running on port 8000");
  }
}
