load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "models",
    srcs = ["Link.java"],
    deps = [
        "@maven//:commons_validator_commons_validator",
        "@maven//:org_json_json",
    ],
)
