/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.thesummit.rook;

import static org.junit.Assert.*;

import org.junit.Test;

public class RookApplicationTest {
  @Test
  public void testAppHasAGreeting() {
    RookApplication classUnderTest = new RookApplication();
    assertNotNull(classUnderTest);
  }
}
