DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS preferences CASCADE;
DROP TABLE IF EXISTS system CASCADE;
DROP TRIGGER IF EXISTS links_update_trigger on links;
DROP FUNCTION IF EXISTS links_modified_timestamp;
DROP EXTENSION IF EXISTS "uuid-ossp";

