load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "database",
    srcs = [
        "ConnectionPool.java",
        "DatabaseObject.java",
        "FlinkConnectionPool.java",
    ],
    deps = [
    ],
)
